### ISSUE TITLE
With 4000+ cores on fishtest, "Base signature" is set to "None" (because GitHub API limit)

### ISSUE THREAD

**Issue by Vizvezdenec** [glinscott/fishtest#385]
When there are this much cores on fishtest I often (and not only I) get this error:
"unable to find branch" and this is master branch which autosets bench to "None" (can't be fixed manually with inputting correct one https://i.imgur.com/U1rkPah.png
This usually autofixes after some time but it's pretty annoying.

**Comment by ppigazzini** [comment]
@Vizvezdenec I think this is a duplicate of https://github.com/glinscott/fishtest/issues/290

**Comment by Vizvezdenec** [comment]
Probably but one thing that it's reasonably frequent now since noobpwn pretty often throws like 3k+ extra cores. So it will be easier to detect what it is :)

**Comment by 31m059** [comment]
The problem appears to be hitting GitHub's API limit.  We're limited to 60 requests/hour unauthenticated, or 5000 requests/hour authenticated.  See https://developer.github.com/v3/#rate-limiting

I apologize that these are beginner questions--I'm not familiar with the inner workings of fishtest--but can someone with knowledge of the worker/server code confirm:
- Does the worker download code from the GitHub API directly, or does the fishtest server download it at the start of the test, cache it, and pass it to later workers as needed?
- Are we using authenticated or unauthenticated access for the GitHub API?

If we're not currently caching the GitHub API response, then passing that to the workers, that seems the most obvious route to make fishtest robust to any number of workers.

**Comment by tomtor** [comment]
@31m059 The worker downloads code from GitHub directly. It uses the normal public download API.

The server accesses the GitHub API authenticated, and it should not exceed the rate limit because access is only when creating a test. The root cause is probably that due to the high worker download pressure, the server access to the API of the same repository is also throttled.

Letting the fishtest server handle the branch download is not a good solution, because it will tax our outgoing bandwidth and the egress budget of the fishtest hosting provider, instead of Microsoft (Github). 

Handing out tasks to new workers could be delayed and throttled as an alternative option, but that would make usage of the worker pool less efficient.
Workers DO cache their downloads and compiles, so the issue will be visible when either a lot of new workers are introduced or a new test is added.

**Comment by tomtor** [comment]
@noobpwnftw If your worker pool could access github with a caching http-proxy then the number of downloads would be reduced. Is adding this an option?

**Comment by 31m059** [comment]
@tomtor Thank you, that makes sense!  

If we do have to handle this server-side: when we have a large number of workers (e.g., 2000+ cores), should we modify worker/task allocation to keep workers on their current test as long as possible (e.g., until the test is stopped or passes/fails) for some period of time ?  Local caching of compiles would then take more load off the API.

**Comment by noobpwnftw** [comment]
@tomtor I also use the same authenticated account for API access on all workers, it should at least trigger my own API limit before hitting anyone else? Note that master compiles are mostly cached, downloads are usually landing on test forks from different users.

Can you check on fishtest server that what exact API endpoint is getting rate limited?

**Comment by tomtor** [comment]
@noobpwnftw The server accesses: https://api.github.com/repos/official-stockfish/Stockfish/commits

The workers access eg https://api.github.com/repos/official-stockfish/Stockfish/zipball/sha

@ppigazzini  Can you see something in the server log at time of failure?

**Comment by noobpwnftw** [comment]
It looks very strange, only when people submit/modify tests, there can be API access from fishtest server. Having a lot of workers has nothing to do with it. Pressure from the worker is spread across different repositories and if it would cause a rate limit then people would have seen failed access to their forks too, which didn't happen, and I have checked that workers during the time were using the same API authentication for things and worked without problem.

So probably it was just too many tests getting submitted/approved/edited.

**Comment by ppigazzini** [comment]
@tomtor unfortunately the script used to sync the server with the latest master lacked the log rotation command. Script fixed now.
@noobpwnftw can you start the worker fleet now?

**Comment by tomtor** [comment]
I remembered adding a key to the server but this was for Google authentication:

https://github.com/glinscott/fishtest/commit/9c56ed0eaafb8a7f00cc0e41bd415d5c5da7425c

So github is still not authenticated and probably just too many tests were created in the window with the larger worker pool as suggested by @noobpwnftw. I will add github authentication in a PR.

**Comment by tomtor** [comment]
@ppigazzini @noobpwnftw just reminded me that we use .netrc for authentication, so we DID already have a high API rate limit...

Weird.

**Comment by noobpwnftw** [comment]
Does the user of which you run the server actually use the .netrc? Should be able to find out by adding a page printing results from `https://api.github.com/rate_limit`.

**Comment by ppigazzini** [comment]
@tomtor @noobpwnftw if I'm using curl correctly then .netrc seems not working. Tested on the server the limit is 60, on my pc I have hit the 60 requests limit simply using that curl sequence

```
~# curl -I https://api.github.com/users/github  --netrc
HTTP/1.1 403 Forbidden
Date: Thu, 05 Sep 2019 09:36:04 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 257
Server: GitHub.com
Status: 403 Forbidden
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1567679560
X-GitHub-Media-Type: github.v3; format=json
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
X-GitHub-Request-Id: 4015:179DC:BE6D47:E6D0A8:5D70D702
```

**Comment by tomtor** [comment]
@noobpwnftw What shows

curl -I https://api.github.com/users/github  --netrc -v

**Comment by ppigazzini** [comment]
@tomtor 
```
~# curl -I https://api.github.com/users/github --netrc -v
* Couldn't find host api.github.com in the .netrc file; using defaults
*   Trying 140.82.118.5...
* TCP_NODELAY set
* Connected to api.github.com (140.82.118.5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS change cipher, Client hello (1):
* (304) (OUT), TLS Unknown, Certificate Status (22):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using unknown / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Jul  8 00:00:00 2019 GMT
*  expire date: Jul 16 12:00:00 2020 GMT
*  subjectAltName: host "api.github.com" matched cert's "*.github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* (304) (OUT), TLS Unknown, Unknown (23):
> HEAD /users/github HTTP/1.1
> Host: api.github.com
> User-Agent: curl/7.58.0
> Accept: */*
>
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Newsession Ticket (4):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Newsession Ticket (4):
* (304) (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Thu, 05 Sep 2019 10:58:30 GMT
Date: Thu, 05 Sep 2019 10:58:30 GMT
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Content-Length: 1330
Content-Length: 1330
< Server: GitHub.com
Server: GitHub.com
< Status: 200 OK
Status: 200 OK
< X-RateLimit-Limit: 60
X-RateLimit-Limit: 60
< X-RateLimit-Remaining: 58
X-RateLimit-Remaining: 58
< X-RateLimit-Reset: 1567684709
X-RateLimit-Reset: 1567684709
< Cache-Control: public, max-age=60, s-maxage=60
Cache-Control: public, max-age=60, s-maxage=60
< Vary: Accept
Vary: Accept
< ETag: "7ec7c38d10980bc9c11a9048bd4e92d8"
ETag: "7ec7c38d10980bc9c11a9048bd4e92d8"
< Last-Modified: Mon, 15 Jul 2019 14:26:15 GMT
Last-Modified: Mon, 15 Jul 2019 14:26:15 GMT
< X-GitHub-Media-Type: github.v3; format=json
X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
X-Frame-Options: deny
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
Content-Security-Policy: default-src 'none'
< Vary: Accept-Encoding
Vary: Accept-Encoding
< X-GitHub-Request-Id: 4357:179DC:D53AAD:102B0A6:5D70EA55
X-GitHub-Request-Id: 4357:179DC:D53AAD:102B0A6:5D70EA55

<
* Connection #0 to host api.github.com left intact
```

**Comment by tomtor** [comment]
@ppigazzini 

First line is not good:

* Couldn't find host api.github.com in the .netrc file; using defaults

**Comment by ppigazzini** [comment]
@tomtor, added api.github.org in .netrc and now the rate limit is up to 5000

```
curl -I https://api.github.com/users/github --netrc -v
*   Trying 140.82.118.5...
* TCP_NODELAY set
* Connected to api.github.com (140.82.118.5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS change cipher, Client hello (1):
* (304) (OUT), TLS Unknown, Certificate Status (22):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using unknown / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Jul  8 00:00:00 2019 GMT
*  expire date: Jul 16 12:00:00 2020 GMT
*  subjectAltName: host "api.github.com" matched cert's "*.github.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Server auth using Basic with user 'ppigazzini'
* (304) (OUT), TLS Unknown, Unknown (23):
> HEAD /users/github HTTP/1.1
> Host: api.github.com
> Authorization: Basic cHBpZ2F6emluaTpnaC5CNHVkMGwxbjAoKQ==
> User-Agent: curl/7.58.0
> Accept: */*
>
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Newsession Ticket (4):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Newsession Ticket (4):
* (304) (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Thu, 05 Sep 2019 11:05:27 GMT
Date: Thu, 05 Sep 2019 11:05:27 GMT
< Content-Type: application/json; charset=utf-8
Content-Type: application/json; charset=utf-8
< Content-Length: 1330
Content-Length: 1330
< Server: GitHub.com
Server: GitHub.com
< Status: 200 OK
Status: 200 OK
< X-RateLimit-Limit: 5000
X-RateLimit-Limit: 5000
< X-RateLimit-Remaining: 4998
X-RateLimit-Remaining: 4998
< X-RateLimit-Reset: 1567685127
X-RateLimit-Reset: 1567685127
< Cache-Control: private, max-age=60, s-maxage=60
Cache-Control: private, max-age=60, s-maxage=60
< Vary: Accept, Authorization, Cookie, X-GitHub-OTP
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
< ETag: "1a3580aea4b29ac913d1d86b3440d4ea"
ETag: "1a3580aea4b29ac913d1d86b3440d4ea"
< Last-Modified: Mon, 15 Jul 2019 14:26:15 GMT
Last-Modified: Mon, 15 Jul 2019 14:26:15 GMT
< X-GitHub-Media-Type: github.v3; format=json
X-GitHub-Media-Type: github.v3; format=json
< Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Frame-Options: deny
X-Frame-Options: deny
< X-Content-Type-Options: nosniff
X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
X-XSS-Protection: 1; mode=block
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< Content-Security-Policy: default-src 'none'
Content-Security-Policy: default-src 'none'
< Vary: Accept-Encoding
Vary: Accept-Encoding
< X-GitHub-Request-Id: 43BE:2260E:12CF496:16AA076:5D70EBF7
X-GitHub-Request-Id: 43BE:2260E:12CF496:16AA076:5D70EBF7

<
* Connection #0 to host api.github.com left intact
```

**Comment by ppigazzini** [comment]
@tomtor my bad, here https://github.com/glinscott/fishtest/pull/239#issuecomment-383670861 you suggested the correct entry for .netrc  (`machine api.github.com`), but I simply used the entry that I was using to push to my repo (`machine github.com`).

**Comment by tomtor** [comment]
> @tomtor my bad, here [#239 (comment)](https://github.com/glinscott/fishtest/pull/239#issuecomment-383670861) you suggested the correct entry for .netrc (`machine api.github.com`), but I simply used the entry that I was using to push to my repo (`machine github.com`).

It is funny that I could not remember this .netrc discussion, but I did vaguely remember that we had worked on the API-limit.

Anyway, we can ignore https://github.com/glinscott/fishtest/pull/388 for now. I will close that one.
