### ISSUE TITLE
'active workers' not doing any test

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#851]
This test has 2 workers which appear active, but don't run any test:

https://tests.stockfishchess.org/tests/view/5f9e7c786a2c112b60691e39
![image](https://user-images.githubusercontent.com/4202567/97808229-03260f80-1c66-11eb-9861-2e2336429e98.png)

their 'active' time is updated and up-to-date, but the test is now over, except for those two workes. 
So probably hung somewhere, but not the heartbeat?

**Comment by vondele** [comment]
I have now stopped and restarted the test to see if that fixes the issue with those two batches.

**Comment by vondele** [comment]
A simple stop/modify didn't help so far. I've stopped it again, and will wait for a bit more before restarting again, to be sure it gets different workers.

**Comment by JojoM-sf** [comment]
Also, Noob's machines will have to be assigned to some other test in the meantime :)

**Comment by JojoM-sf** [comment]
The two respective machines are back, it would seem ... active, but doing any testing.

**Comment by vondele** [comment]
yes, now after a longer wait, these batches are being computed.

**Comment by JojoM-sf** [comment]
Done, and with a good result.
Issue resolved, I think.

**Comment by vondele** [comment]
no issue not quite resolved. We need to understand how these workers ended up in that state.

**Comment by JojoM-sf** [comment]
True. But then maybe @noobpwnftw would have to tell us about the output he got ...

**Comment by snicolet** [comment]
@vondele Could it be that the workers were hit by the bug discussed in https://github.com/official-stockfish/Stockfish/issues/3216 , so that Stockfish would crash on bench for them?

**Comment by vondele** [comment]
no, I don't think so, first, that bug is newer than this issue, and a crashing compile should not lead to this behavior. (Also these are noob workers, so not windows, and stable). Hard to guess what it would be, but possibly something network that doesn't timeout? idk.

**Comment by tomtor** [comment]
I noticed that at least one of the `dew` machines constantly report failures almost directly after receiving/completing their task?

```
Nov  6 15:01:05 tests pserve[1708]: Allocate run: 5fa40e365d72639a7acef79e task_id: 310 to 6c3861c6-370e-4f83-81dd-8705a5ea5224
Nov  6 15:01:12 tests pserve[1708]: Failed 5fa40e365d72639a7acef79e {'num_games': 200, 'pending': True, 'active': True, 'last_updated': datetime.datetime(2020, 11, 6, 15, 1, 5, 776458), 'worker_key': '-', 'residual': 0.0, 'residual_color': '#44EB44', 'worker_info': {'uname': 'Linux 3.18.9-hardened', 'concurrency': 5, 'architecture': ['64bit', 'ELF'], 'username': 'dew', 'max_memory': 8010, 'rate': {'remaining': 60, 'used': 0, 'reset': 1604678464, 'limit': 60}, 'version': '92:3', 'min_threads': 1, 'unique_key': '6c3861c6-370e-4f83-81dd-8705a5ea5224', 'remote_addr': '81.95.137.18', 'country_code': 'RU'}, 'stats': {'wins': 0, 'losses': 0, 'draws': 0, 'pentanomial': [0, 0, 0, 0, 0]}}
```

**Comment by vondele** [comment]
that's @d3vv maybe he can have a look at the logs of the machine on 81.95.137.18 to check if he sees anything special?

**Comment by tomtor** [comment]
@vondele @ppigazzini I found some broken logic: https://github.com/glinscott/fishtest/pull/857/commits/44dbad8b7b4d796eac1c04ba7d0a3266b7cda7fc

A reallocated task would be dropped from the new worker when the old worker signalled that his task failed.
This process can repeat itself.

The correct fix would be to test for worker `unique_key` but that requires a worker upgrade, so for now I just test for the username and will file a PR for the worker.

Note that @d3vv worker is still looping:

```
Nov  7 09:42:12 tests pserve[8232]: Inactive: https://tests.stockfishchess.org/tests/view/5fa5bdaa936c54e11ec99539 406 dew-5cores
Nov  7 09:42:35 tests pserve[8232]: Inactive: https://tests.stockfishchess.org/tests/view/5fa66b06aa9fe6d8cf2dcf68 0 dew-5cores
Nov  7 09:42:58 tests pserve[8232]: Inactive: https://tests.stockfishchess.org/tests/view/5fa66b06aa9fe6d8cf2dcf68 2 dew-5cores
Nov  7 09:43:22 tests pserve[8232]: Inactive: https://tests.stockfishchess.org/tests/view/5fa60053936c54e11ec99563 369 dew-5cores
Nov  7 09:43:45 tests pserve[8232]: Inactive: https://tests.stockfishchess.org/tests/view/5fa5b553936c54e11ec99526 428 dew-5cores
Nov  7 09:44:09 tests pserve[8232]: Inactive: https://tests.stockfishchess.org/tests/view/5fa60053936c54e11ec99563 372 dew-5cores
Nov  7 09:44:32 tests pserve[8232]: Inactive: https://tests.stockfishchess.org/tests/view/5fa5dfd8936c54e11ec99547 480 dew-5cores

```

**Comment by ppigazzini** [comment]
@tomtor we should be able to trigger immediately a worker update, see https://github.com/glinscott/fishtest/pull/845#issuecomment-720061178

**Comment by tomtor** [comment]
> @tomtor we should be able to trigger immediately a worker update, see [#845 (comment)](https://github.com/glinscott/fishtest/pull/845#issuecomment-720061178)

Yes, when https://github.com/glinscott/fishtest/pull/858 is merged and the workers are updated, then I could adapt #857 

@ppigazzini There is no hurry however. Would you like me to add the version number bumps (server and worker) upgrades to #858 ?

**Comment by ppigazzini** [comment]
@tomtor when ready please add the version bump (worker and server side).

**Comment by tomtor** [comment]
> @tomtor when ready please add the version bump (worker and server side).

@ppigazzini Bumped and pushed

**Comment by d3vv** [comment]
@vondele here's the "log":

`Step 1/4. Building instrumented executable ...
make ARCH=x86-64-ssse3 COMP=gcc gcc-profile-make
make[1]: Entering directory '/home/dew/fishtest/worker/tmprzuh6lwt/snicolet-Stockfish-6351de0/src'
make ARCH=x86-64-ssse3 COMP=gcc \
EXTRACXXFLAGS='-fprofile-generate' \
EXTRALDFLAGS='-lgcov' \
all
make[2]: Entering directory '/home/dew/fishtest/worker/tmprzuh6lwt/snicolet-Stockfish-6351de0/src'
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o benchmark.o benchmark.cpp
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o bitbase.o bitbase.cpp
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o bitboard.o bitboard.cpp
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o endgame.o endgame.cpp
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o evaluate.o evaluate.cpp
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o main.o main.cpp
In file included from nnue/architectures/halfkp_256x2-32-32.h:28:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from benchmark.cpp:24:
nnue/architectures/../layers/affine_transform.h: In member function 'const OutputType* Eval::NNUE::Layers::AffineTransform<PreviousLayer, OutputDimensions>::Propagate(const TransformedFeatureType*, char*) const':
nnue/architectures/../layers/affine_transform.h:160:38: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] const __m128i kOnes128 = _mm_set1_epi16(1);
                                      ^~~~~~~~
nnue/architectures/../layers/affine_transform.h:162:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_hadd = [](__m128i sum, int bias) -> int {
                             ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:168:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_haddx4 = [](__m128i sum0, __m128i sum1, __m128i sum2, __m128i sum3, __m128i bias) -> __m128i {
                             ^~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:177:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_add_dpbusd_epi32 = [=](__m128i& acc, __m128i a, __m128i b) {
                             ^~~~~~~~~~~~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:385:10: error: expected '(' before 'constexpr'
       if constexpr (kOutputDimensions % 4 == 0)
          ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:541:5: error: expected '}' at end of input
     }
     ^
nnue/architectures/../layers/affine_transform.h:541:5: warning: no return statement in function returning non-void [-Wreturn-type]
In file included from nnue/architectures/halfkp_256x2-32-32.h:28:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from endgame.h:28,
                 from endgame.cpp:22:
nnue/architectures/../layers/affine_transform.h: In member function 'const OutputType* Eval::NNUE::Layers::AffineTransform<PreviousLayer, OutputDimensions>::Propagate(const TransformedFeatureType*, char*) const':
nnue/architectures/../layers/affine_transform.h:160:38: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] const __m128i kOnes128 = _mm_set1_epi16(1);
                                      ^~~~~~~~
nnue/architectures/../layers/affine_transform.h:162:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_hadd = [](__m128i sum, int bias) -> int {
                             ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:168:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_haddx4 = [](__m128i sum0, __m128i sum1, __m128i sum2, __m128i sum3, __m128i bias) -> __m128i {
                             ^~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:177:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_add_dpbusd_epi32 = [=](__m128i& acc, __m128i a, __m128i b) {
                             ^~~~~~~~~~~~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:385:10: error: expected '(' before 'constexpr'
       if constexpr (kOutputDimensions % 4 == 0)
          ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:541:5: error: expected '}' at end of input
     }
     ^
nnue/architectures/../layers/affine_transform.h:541:5: warning: no return statement in function returning non-void [-Wreturn-type]
g++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DUSE_PTHREADS -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -flto   -c -o material.o material.cpp
make[2]: *** [<builtin>: benchmark.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from nnue/architectures/halfkp_256x2-32-32.h:28:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from endgame.h:28,
                 from material.h:22,
                 from evaluate.cpp:32:
nnue/architectures/../layers/affine_transform.h: In member function 'const OutputType* Eval::NNUE::Layers::AffineTransform<PreviousLayer, OutputDimensions>::Propagate(const TransformedFeatureType*, char*) const':
nnue/architectures/../layers/affine_transform.h:160:38: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] const __m128i kOnes128 = _mm_set1_epi16(1);
                                      ^~~~~~~~
nnue/architectures/../layers/affine_transform.h:162:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_hadd = [](__m128i sum, int bias) -> int {
                             ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:168:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_haddx4 = [](__m128i sum0, __m128i sum1, __m128i sum2, __m128i sum3, __m128i bias) -> __m128i {
                             ^~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:177:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_add_dpbusd_epi32 = [=](__m128i& acc, __m128i a, __m128i b) {
                             ^~~~~~~~~~~~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:385:10: error: expected '(' before 'constexpr'
       if constexpr (kOutputDimensions % 4 == 0)
          ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:541:5: error: expected '}' at end of input
     }
     ^
nnue/architectures/../layers/affine_transform.h:541:5: warning: no return statement in function returning non-void [-Wreturn-type]
make[2]: *** [<builtin>: endgame.o] Error 1
evaluate.cpp: In member function 'void {anonymous}::Evaluation<T>::initialize()':
evaluate.cpp:370:28: error: 'clamp' is not a member of 'std'
     Square s = make_square(std::clamp(file_of(ksq), FILE_B, FILE_G),
                            ^~~
evaluate.cpp:371:28: error: 'clamp' is not a member of 'std'
                            std::clamp(rank_of(ksq), RANK_2, RANK_7));
                            ^~~
evaluate.cpp: In member function 'Value {anonymous}::Evaluation<T>::winnable(Score) const':
evaluate.cpp:882:37: error: 'clamp' is not a member of 'std'
     int u = ((mg > 0) - (mg < 0)) * std::clamp(complexity + 50, -abs(mg), 0);
                                     ^~~
evaluate.cpp: In function 'Value Eval::evaluate(const Position&)':
evaluate.cpp:1055:7: error: 'clamp' is not a member of 'std'
   v = std::clamp(v, VALUE_TB_LOSS_IN_MAX_PLY + 1, VALUE_TB_WIN_IN_MAX_PLY - 1);
       ^~~
In file included from nnue/architectures/halfkp_256x2-32-32.h:28:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from endgame.h:28,
                 from main.cpp:22:
nnue/architectures/../layers/affine_transform.h: In member function 'const OutputType* Eval::NNUE::Layers::AffineTransform<PreviousLayer, OutputDimensions>::Propagate(const TransformedFeatureType*, char*) const':
nnue/architectures/../layers/affine_transform.h:160:38: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] const __m128i kOnes128 = _mm_set1_epi16(1);
                                      ^~~~~~~~
nnue/architectures/../layers/affine_transform.h:162:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_hadd = [](__m128i sum, int bias) -> int {
                             ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:168:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_haddx4 = [](__m128i sum0, __m128i sum1, __m128i sum2, __m128i sum3, __m128i bias) -> __m128i {
                             ^~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:177:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_add_dpbusd_epi32 = [=](__m128i& acc, __m128i a, __m128i b) {
                             ^~~~~~~~~~~~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:385:10: error: expected '(' before 'constexpr'
       if constexpr (kOutputDimensions % 4 == 0)
          ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:541:5: error: expected '}' at end of input
     }
     ^
nnue/architectures/../layers/affine_transform.h:541:5: warning: no return statement in function returning non-void [-Wreturn-type]
make[2]: *** [<builtin>: evaluate.o] Error 1
In file included from nnue/architectures/halfkp_256x2-32-32.h:28:0,
                 from nnue/nnue_architecture.h:25,
                 from nnue/nnue_accumulator.h:24,
                 from position.h:31,
                 from endgame.h:28,
                 from material.h:22,
                 from material.cpp:22:
nnue/architectures/../layers/affine_transform.h: In member function 'const OutputType* Eval::NNUE::Layers::AffineTransform<PreviousLayer, OutputDimensions>::Propagate(const TransformedFeatureType*, char*) const':
nnue/architectures/../layers/affine_transform.h:160:38: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] const __m128i kOnes128 = _mm_set1_epi16(1);
                                      ^~~~~~~~
nnue/architectures/../layers/affine_transform.h:162:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_hadd = [](__m128i sum, int bias) -> int {
                             ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:168:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_haddx4 = [](__m128i sum0, __m128i sum1, __m128i sum2, __m128i sum3, __m128i bias) -> __m128i {
                             ^~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:177:29: warning: 'maybe_unused' attribute directive ignored [-Wattributes]
       [[maybe_unused]] auto m128_add_dpbusd_epi32 = [=](__m128i& acc, __m128i a, __m128i b) {
                             ^~~~~~~~~~~~~~~~~~~~~
nnue/architectures/../layers/affine_transform.h:385:10: error: expected '(' before 'constexpr'
       if constexpr (kOutputDimensions % 4 == 0)
          ^~~~~~~~~
nnue/architectures/../layers/affine_transform.h:541:5: error: expected '}' at end of input
     }
     ^
nnue/architectures/../layers/affine_transform.h:541:5: warning: no return statement in function returning non-void [-Wreturn-type]
material.cpp: In function 'Material::Entry* Material::probe(const Position&)':
material.cpp:133:17: error: 'clamp' is not a member of 'std'
   Value npm   = std::clamp(npm_w + npm_b, EndgameLimit, MidgameLimit);
                 ^~~
make[2]: *** [<builtin>: main.o] Error 1
make[2]: *** [<builtin>: material.o] Error 1
make[2]: Leaving directory '/home/dew/fishtest/worker/tmprzuh6lwt/snicolet-Stockfish-6351de0/src'
make[1]: *** [Makefile:859: gcc-profile-make] Error 2
make[1]: Leaving directory '/home/dew/fishtest/worker/tmprzuh6lwt/snicolet-Stockfish-6351de0/src'
make: *** [Makefile:720: profile-build] Error 2

Exception running games:
Traceback (most recent call last):
  File "/home/dew/fishtest/worker/games.py", line 414, in setup_engine
    shell=True, env=dict(os.environ, CXXFLAGS="-DNNUE_EMBEDDING_OFF")
  File "/usr/lib64/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make COMP=gcc ARCH=x86-64-ssse3 -j 5 profile-build' returned non-zero exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fishtest/worker/worker.py", line 220, in worker
  File "/home/dew/fishtest/worker/games.py", line 884, in run_games
    worker_info["concurrency"],
  File "/home/dew/fishtest/worker/games.py", line 425, in setup_engine
    raise Exception("Failed to setup engine for {}".format(sha))
Exception: Failed to setup engine for 6351de009dfb4463ce2d679c18bbca2ed82e897b
Task exited
^CSend heartbeat... Traceback (most recent call last):
  File "fishtest/worker/worker.py", line 449, in <module>
    main()
  File "fishtest/worker/worker.py", line 444, in main
    time.sleep(HTTP_TIMEOUT)
  File "fishtest/worker/worker.py", line 95, in on_sigint
    raise Exception("Terminated by signal")
Exception: Terminated by signal
Pleased to hear from you...`

**Comment by vondele** [comment]
@d3vv which version of gcc do you have on the system? I think we require gcc 7.3, but it would be useful to know what you have.

Maybe we need to be able to catch this behavior in the worker somehow, and signal that to the user.

**Comment by d3vv** [comment]
@vondele gcc 6.4 - it is my fault.. I stopped worker and  will do upgrade soon

**Comment by d3vv** [comment]
@ppigazzini It would be nice to have the possibility to check worker by UID on host. It is to hard find the desired worker when there are several servers at the same IP via NAT.

**Comment by tomtor** [comment]
> @ppigazzini It would be nice to have the possibility to check worker by UID on host. It is to hard find the desired worker when there are several servers at the same IP via NAT.

@d3vv Yes, good suggestion, we should print the UUID.

The hartbeat message would be a good place. Will create a PR for that.

**Comment by d3vv** [comment]
@tomtor It would also be nice to print the last UID to a file - quick to check "cat <file>" and find it.. Otherwise in my case I need call screen/tmux(inconvenient time-consuming action) and will see several lines from worker output.. Moreover if too much errors/output from worker I may not see that UID..

**Comment by d3vv** [comment]
I got the worker back with gcc 10.2
Can anyone clarify if there are any problems with other workers?

**Comment by tomtor** [comment]
>  Can anyone clarify if there are any problems with other workers?

Your other workers are fine!

**Comment by tomtor** [comment]
If this still happens I would like to know, because recent fishtest changes should have fixed this.

Closing for now.
